REQUEST FOR CODE REVIEW ON JAVASCRIPT TO-DO LIST PROJECT
Moreneecoder/task-hero pull request #1
Opened 2021-07-31 22:38 UTC by Moreneecoder

In this project, I built a to-do app that allows users to manage tasks and sort them into projects. The project makes use of Javascript and the Webpack bundler. I also modularized the code to enable a DRY and clean code pattern. While I am yet to implement all required features on this project, I thought it best to submit it for review. This is so I can get early feedback from a TSE on the project.

2021-08-01 04:08 UTC, elisha2kyakpo1 requested changes
Hi, @Moreneecoder, 

Good job so far! I like the project setup as well as the codebase.
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  I wasn't able to delete or edit a to-do item, this is a requirement for this project.
- [ ] When I clicked the new task button, the popup opens, but I can't create anything from this popup.
- [ ] The default projects could not allow me to create a to-do from them, they are static.

_Check other comments under the review._ 👇 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


### Cheers and Happy coding!👏👏👏

**__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-08-01 04:08 UTC, elisha2kyakpo1 commented on src/components/appCompontents/app.js
> +  projects.forEach((project) => {
- [ ] I was unable to create a new project, the project requirement is that a user should be able to create a new project

2021-08-01 04:08 UTC, elisha2kyakpo1 commented on src/index.js
> +//   document.body.appendChild(component());
- [ ] please, remove this commented code, remember to leave the codebase clean, if you need any of the old code, you can use GitHub history.

2021-08-05 22:20 UTC, taiwo2 requested changes
# STATUS: APPROVED ♻️ 
@Moreneecoder well done on this project work and thanks for implementing some of the suggested changes, however, changes are required
### Highlight

- I was able to delete or edit a to-do item, this is a requirement for this project. 👍🏻 
-  When I clicked the new task button, the popup opens, I was able to create from the popup. 👍🏻

 
### Improve 

- [ ] The default projects should be static i.e should not be edited or delete or create a to-do from them. they should serve as example for users

### once fixed kindly request for review

2021-08-06 10:19 UTC, Moreneecoder commented
The last two reviewers have conflicting opinions on the default project. The first, Elisha, says the default project should not be static, as he expects a user to be able to create and modify todos from them (the default welcome project). The second reviewer, Taiwo, said totally otherwise. This is seriously confusing and tiring because it is the only aspect of this project holding me from approval. I think the first reviewer is right, however, because, I don't see why the default project should be static. Other apps like Todoist, don't have a static default project. It's totally dynamic.

2021-08-06 10:40 UTC, afanimartin approved these changes
## Approved 👍🏿 👍🏿 👍🏿 
Sorry for the confusion. I think from the requirements we are only expected to have a default project. Merge and proceed to the next project.


### Martin Afani
#### Slack: whiz25

2021-08-06 10:45 UTC, merged